# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
name:               "CCM Lab"
title:              "CCM Lab at The University of British Columbia"
description:        "The CCM Lab is a research group at The University of British Columbia studying human motor learning."


# URL
url:                http://ccmlab.org 
baseurl:            
#baseurl:            "" #For Root Domain
permalink:          /:year/:month/:day/:title.html

# Markdown
markdown:           kramdown

# Highlighter
highlighter:        rouge

# Navigation
nav:
  - name:           "home"
    href:           "/"
  - name:           "about"
    href:           "/about"
  - name:           "people"
    href:           "/people"
  - name:           "publications"
    href:           "/publication"
#   - name:           "blog"
#     href:           "/blog"
#   - name:           "resources"
#     href:           "/resources"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
  -
    scope:
      path:         ""
      type:         "people"
    values:
      layout:       "profile"


collections:
  people:
    output: true
    permalink: /people/:title/index.html
